apiVersion: v1
kind: Pod
metadata: 
  name: demo
spec: 
  containers: 
    - 
      image: "registry.hub.docker.com/qwertiq/demo-repo:0.0.1-SNAPSHOT"
      name: demo
      ports: 
        - 
          containerPort: 8080
          name: http
          protocol: TCP
